/**
 * Stats — baked offline fallback + curated hero set.
 *
 * Live authority is the BFF `/stats` endpoint (fetched by WorkGraphProvider).
 * `stats-baked.json` is generated by `bun scripts/sync-stats.mjs` and is the
 * only aggregate fallback the site may ship. Pre-cut values are null until a
 * `public-only/v1` response regenerates them, so unverifiable numbers are never
 * presented as stale or fresh.
 *
 * Career-scale figures (years, app downloads, monthly players) are
 * self-attested historical pedigree. They must not appear on the hero
 * proof board or use freshness=live vocabulary.
 */
import baked from "@/data/stats-baked.json";
import type { ClaimHonesty } from "./claim-honesty";

export interface BakedStats {
  verifiedAt: string | null;
  source: string | null;
  repositoryVisibility: string;
  githubStars: number | null;
  npmDownloads: number | null;
  flagshipStars: number | null;
  flagshipDownloads: number | null;
  repos: number | null;
  updatedAt: string | null;
}

export const BAKED_STATS: BakedStats = baked;

export interface Stat {
  id: string;
  value: number | null;
  display: string;
  label: string;
  source: string; // URL or short attestation note
  honesty: ClaimHonesty;
  verifiedAt?: string | null;
}

const compactFmt = new Intl.NumberFormat("en-US", {
  notation: "compact",
  maximumFractionDigits: 1,
});

function compact(n: number | null): string {
  return n === null ? "—" : compactFmt.format(n);
}

export const STATS: Record<string, Stat> = {
  yearsExperience: {
    id: "years",
    value: 20,
    display: "20+",
    label: "Years building",
    source: "Career since Nakuz (2006)",
    honesty: "self-attested",
  },
  appDownloads: {
    id: "downloads",
    value: 10_000_000,
    display: "10M+",
    label: "App downloads",
    source: "Cubeage — global mobile game installs",
    honesty: "self-attested",
  },
  monthlyPlayers: {
    id: "players",
    value: 10_000_000,
    display: "10M+",
    label: "Monthly players",
    source: "MiniMax / Funimax — peak Facebook MAU",
    honesty: "self-attested",
  },
  githubStars: {
    id: "stars",
    value: baked.githubStars,
    display: compact(baked.githubStars),
    label: "GitHub stars",
    source: "Live: SylphxAI + @shtse8 + Cubeage / EpiowAI (non-fork)",
    honesty: "live-measured",
    verifiedAt: baked.verifiedAt,
  },
  npmDownloads: {
    id: "npm-downloads",
    value: baked.npmDownloads,
    display: compact(baked.npmDownloads),
    label: "npm downloads / month",
    source: "@sylphx + @shtse8 packages — npm last-month",
    honesty: "live-measured",
    verifiedAt: baked.verifiedAt,
  },
  flagshipStars: {
    id: "flagship-stars",
    value: baked.flagshipStars,
    display: compact(baked.flagshipStars),
    label: "Stars · pdf-reader-mcp",
    source: "github.com/SylphxAI/pdf-reader-mcp",
    honesty: "live-measured",
    verifiedAt: baked.verifiedAt,
  },
  flagshipDownloads: {
    id: "flagship-downloads",
    value: baked.flagshipDownloads,
    display: compact(baked.flagshipDownloads),
    label: "Downloads / mo · pdf-reader-mcp",
    source: "npmjs.com/package/@sylphx/pdf-reader-mcp — last-month",
    honesty: "live-measured",
    verifiedAt: baked.verifiedAt,
  },
  repos: {
    id: "repos",
    value: baked.repos,
    display: compact(baked.repos),
    label: "Public repositories",
    source: "GitHub aggregate across owned orgs",
    honesty: "live-measured",
    verifiedAt: baked.verifiedAt,
  },
};

/** Hero proof-board instruments — live-measured GitHub/npm only. */
export const HERO_PROOF = {
  githubStars: STATS.githubStars,
  npmDownloads: STATS.npmDownloads,
  flagshipStars: STATS.flagshipStars,
  flagshipDownloads: STATS.flagshipDownloads,
} as const;

export const HERO_STATS: Stat[] = [
  HERO_PROOF.githubStars,
  HERO_PROOF.npmDownloads,
  HERO_PROOF.flagshipStars,
  HERO_PROOF.flagshipDownloads,
];
