/**
 * Stats — baked offline fallback + curated hero set.
 *
 * Live authority is the BFF `/stats` endpoint (fetched by WorkGraphProvider).
 * `stats-baked.json` is generated by `bun scripts/sync-stats.mjs` and is the
 * only fallback the site ships; every value carries a `verifiedAt` timestamp
 * so stale numbers are never presented as fresh.
 */
import baked from "@/data/stats-baked.json";

export interface BakedStats {
  verifiedAt: string;
  source: string;
  githubStars: number;
  npmDownloads: number;
  flagshipStars: number;
  flagshipDownloads: number;
  repos: number;
  updatedAt: string;
}

export const BAKED_STATS: BakedStats = baked;

export interface Stat {
  id: string;
  value: number;
  display: string;
  label: string;
  source: string; // URL or short attestation note
  verifiedAt?: string;
}

const compactFmt = new Intl.NumberFormat("en-US", {
  notation: "compact",
  maximumFractionDigits: 1,
});

function compact(n: number): string {
  return compactFmt.format(n);
}

export const STATS: Record<string, Stat> = {
  yearsExperience: {
    id: "years",
    value: 20,
    display: "20+",
    label: "Years building",
    source: "Career since Nakuz (2006)",
  },
  appDownloads: {
    id: "downloads",
    value: 10_000_000,
    display: "10M+",
    label: "App downloads",
    source: "Cubeage — global mobile game installs",
  },
  monthlyPlayers: {
    id: "players",
    value: 10_000_000,
    display: "10M+",
    label: "Monthly players",
    source: "MiniMax / Funimax — peak Facebook MAU",
  },
  githubStars: {
    id: "stars",
    value: baked.githubStars,
    display: compact(baked.githubStars),
    label: "GitHub stars",
    source: "Live: SylphxAI + @shtse8 + Cubeage / EpiowAI (non-fork)",
    verifiedAt: baked.verifiedAt,
  },
  npmDownloads: {
    id: "npm-downloads",
    value: baked.npmDownloads,
    display: compact(baked.npmDownloads),
    label: "npm downloads / month",
    source: "@sylphx + @shtse8 packages — npm last-month",
    verifiedAt: baked.verifiedAt,
  },
  flagshipStars: {
    id: "flagship-stars",
    value: baked.flagshipStars,
    display: compact(baked.flagshipStars),
    label: "Stars · pdf-reader-mcp",
    source: "github.com/SylphxAI/pdf-reader-mcp",
    verifiedAt: baked.verifiedAt,
  },
  flagshipDownloads: {
    id: "flagship-downloads",
    value: baked.flagshipDownloads,
    display: compact(baked.flagshipDownloads),
    label: "Downloads / mo · pdf-reader-mcp",
    source: "npmjs.com/package/@sylphx/pdf-reader-mcp — last-month",
    verifiedAt: baked.verifiedAt,
  },
  repos: {
    id: "repos",
    value: baked.repos,
    display: compact(baked.repos),
    label: "Public repositories",
    source: "GitHub aggregate across owned orgs",
    verifiedAt: baked.verifiedAt,
  },
};

/** Curated 4-stat set for the hero — AI-adoption first, then scale credibility. */
export const HERO_STATS: Stat[] = [
  STATS.npmDownloads,
  STATS.githubStars,
  STATS.appDownloads,
  STATS.yearsExperience,
];
