#!/usr/bin/env python3
"""Brand home generator: rebuilds every derived file in brand/ from the SVG masters.

    python3 brand/build.py            # regenerate (needs: pip install pillow resvg-py numpy)
    python3 brand/build.py --resnap   # also redraw the 16/32 px grids from the master
    python3 brand/build.py --check    # verify hashes and surface copies (stdlib only; for CI)

brand/brand.json says which master feeds which output and which surface files
are copies of brand files. brand/README.md is the usage sheet.

Small sizes are pixel-snapped: the master is rendered at 8x and every sample
takes the nearest brand colour from tokens.json (or empty). A pixel takes the
colour most of its samples agree on, and stays empty when fewer than the
threshold of its samples are filled. The result
is stored as a character grid (favicon/grid-16.txt, grid-32.txt) that a
person may hand-edit; later runs draw from the grid until --resnap.
"""
import hashlib, io, json, os, shutil, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPEC = json.load(open(os.path.join(HERE, 'brand.json')))
TOKENS = json.load(open(os.path.join(HERE, 'tokens.json')))
GRID_CHARS = '.ABCDEFGHIJKLMNOPQRSTUVWXYZ'


def p(rel):
    return os.path.join(HERE, rel)


def sha(path):
    return hashlib.sha256(open(path, 'rb').read()).hexdigest()


def colour_tokens():
    out = {}
    for name, tok in TOKENS.get('color', {}).items():
        out[name] = tok['$value'] if isinstance(tok, dict) else tok
    return out


# ---------------------------------------------------------------- tokens.css
def write_tokens_css():
    lines = ['/* Generated by brand/build.py from brand/tokens.json. Do not edit. */', ':root {']
    for group, items in TOKENS.items():
        if group.startswith('$') or not isinstance(items, dict):
            continue
        for name, tok in items.items():
            v = tok['$value'] if isinstance(tok, dict) else tok
            if isinstance(v, list):
                v = ', '.join(v)
            lines.append(f'  --brand-{group}-{name}: {v};')
    lines.append('}')
    open(p('tokens.css'), 'w').write('\n'.join(lines) + '\n')


# ---------------------------------------------------------------- rendering
def render(svg_rel, w, h=None):
    import resvg_py
    from PIL import Image
    h = h or w
    png = resvg_py.svg_to_bytes(svg_path=p(svg_rel), width=w, height=h)
    img = Image.open(io.BytesIO(bytes(png))).convert('RGBA')
    if img.size != (w, h):   # a non-square master keeps its aspect ratio: centre it on the canvas
        img.thumbnail((w, h), Image.LANCZOS)
        canvas = Image.new('RGBA', (w, h), (0, 0, 0, 0))
        canvas.paste(img, ((w - img.width) // 2, (h - img.height) // 2))
        img = canvas
    return img


def save_png(img, rel):
    """Save by extension: .png (optimised), .jpg/.jpeg (quality 85), .webp."""
    os.makedirs(os.path.dirname(p(rel)), exist_ok=True)
    if rel.lower().endswith(('.jpg', '.jpeg')):
        img.convert('RGB').save(p(rel), quality=85, optimize=True, progressive=True)
    else:
        img.save(p(rel), optimize=True)


def hex_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def snap(svg_rel, size, threshold, palette):
    """Render at 8x and quantise every sample to the nearest palette colour (or empty when
    under half opaque). A pixel takes the colour most of its samples agree on, and stays
    empty when fewer than `threshold` of its samples are filled."""
    import numpy as np
    ss = 8
    a = np.asarray(render(svg_rel, size * ss), dtype=np.float64) / 255.0
    pal = np.array([hex_rgb(c) for c in palette], dtype=np.float64) / 255.0
    d = ((a[..., None, :3] - pal[None, None]) ** 2).sum(axis=-1)
    idx = d.argmin(axis=-1) + 1
    idx[a[..., 3] < 0.5] = 0
    idx = idx.reshape(size, ss, size, ss).transpose(0, 2, 1, 3).reshape(size, size, ss * ss)
    rows = []
    for y in range(size):
        row = ''
        for x in range(size):
            counts = np.bincount(idx[y, x], minlength=len(palette) + 1)
            filled = counts[1:].sum() / (ss * ss)
            row += '.' if filled < threshold else GRID_CHARS[1 + int(counts[1:].argmax())]
        rows.append(row)
    return rows


def grid_path(size):
    return f'favicon/grid-{size}.txt'


def write_grid(size, rows, palette):
    header = [f'# {size}x{size} pixel grid for the favicon. "." is empty; letters index the palette below.',
              '# Hand edits are kept: build.py draws from this file until --resnap.']
    header += [f'# {GRID_CHARS[i + 1]} = {c}' for i, c in enumerate(palette)]
    open(p(grid_path(size)), 'w').write('\n'.join(header + rows) + '\n')


def read_grid(size):
    rows, pal = [], {}
    for line in open(p(grid_path(size))):
        line = line.rstrip('\n')
        if line.startswith('# ') and ' = #' in line:
            k, v = line[2:].split(' = ')
            pal[k.strip()] = v.strip()
        elif line and not line.startswith('#'):
            rows.append(line)
    assert len(rows) == size and all(len(r) == size for r in rows), f'grid-{size} must be {size}x{size}'
    return rows, pal


def grid_png(rows, pal, size):
    from PIL import Image
    img = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    for y, r in enumerate(rows):
        for x, ch in enumerate(r):
            if ch != '.':
                img.putpixel((x, y), hex_rgb(pal[ch]) + (255,))
    return img


def grid_svg(rows, pal, size, dark_map=None):
    """Pixel grid as one path per colour, run-length merged along rows. dark_map swaps
    colours when the browser is in a dark theme."""
    paths = {}
    for y, r in enumerate(rows):
        x = 0
        while x < size:
            ch = r[x]
            if ch == '.':
                x += 1
                continue
            x0 = x
            while x < size and r[x] == ch:
                x += 1
            paths.setdefault(ch, []).append(f'M{x0} {y}h{x - x0}v1h-{x - x0}z')
    dark = {ch: dark_map[c] for ch, c in pal.items() if dark_map and c in dark_map}
    style = ''
    if dark:
        rules = ''.join(f'.{ch}{{fill:{c}}}' for ch, c in sorted(dark.items()))
        style = f'<style>@media (prefers-color-scheme:dark){{{rules}}}</style>'
    body = ''.join(f'<path{" class=" + chr(34) + ch + chr(34) if ch in dark else ""} fill="{pal[ch]}" d="{"".join(d)}"/>'
                   for ch, d in sorted(paths.items()))
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" '
            f'shape-rendering="crispEdges">{style}{body}</svg>\n')


def write_ico(images, rel):
    """ICO holding PNG entries (one per size, drawn separately)."""
    blobs = []
    for img in images:
        b = io.BytesIO()
        img.save(b, format='PNG', optimize=True)
        blobs.append((img.size[0], b.getvalue()))
    out = struct.pack('<HHH', 0, 1, len(blobs))
    offset = 6 + 16 * len(blobs)
    for size, data in blobs:
        out += struct.pack('<BBBBHHII', size % 256, size % 256, 0, 0, 1, 32, len(data), offset)
        offset += len(data)
    out += b''.join(d for _, d in blobs)
    open(p(rel), 'wb').write(out)


# ---------------------------------------------------------------- build
def build(resnap):
    write_tokens_css()
    if 'icon' in SPEC:
        build_icons(SPEC['icon'], resnap)
    for r in renders():
        img = render(r['master'], r.get('width', 1200), r.get('height', 630))
        save_png(img if r.get('alpha') else img.convert('RGB'), r['out'])
    copy_outputs()
    write_provenance()


def build_icons(icon, resnap):
    small_src = icon.get('small', icon['master'])
    palette = icon.get('palette') or list(colour_tokens().values())
    thr = icon.get('snap_threshold', 0.5)
    os.makedirs(p('favicon'), exist_ok=True)
    smalls = {}
    for size in (16, 32):
        if resnap or not os.path.exists(p(grid_path(size))):
            write_grid(size, snap(small_src, size, thr, palette), palette)
        rows, pal = read_grid(size)
        smalls[size] = grid_png(rows, pal, size)
        save_png(smalls[size], f'favicon/favicon-{size}.png')
        if size == 32:
            open(p('favicon/favicon.svg'), 'w').write(grid_svg(rows, pal, size, icon.get('dark_map')))
    r48 = render(small_src, 48)
    save_png(r48, 'favicon/favicon-48.png')
    write_ico([smalls[16], smalls[32], r48], 'favicon/favicon.ico')
    for size in icon.get('sizes', [180, 192, 512, 1024]):
        name = 'apple-touch-icon-180.png' if size == 180 else f'icon-{size}.png'
        src = icon.get('apple_touch', icon['master']) if size == 180 else icon['master']
        save_png(render(src, size).convert('RGB') if size == 180 else render(src, size), f'app-icon/{name}')
    if icon.get('maskable'):
        for size in icon.get('maskable_sizes', [192, 512]):
            save_png(render(icon['maskable'], size), f'app-icon/icon-maskable-{size}.png')


def renders():
    """Extra renders: social images ("og") and any other fixed-size file ("renders")."""
    return SPEC.get('og', []) + SPEC.get('renders', [])


def copy_outputs():
    for surface, rel in SPEC.get('outputs', {}).items():
        dst = os.path.join(ROOT, surface)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(p(rel), dst)


def brand_files():
    skip = {'provenance.json'}
    for d, _, files in os.walk(HERE):
        if '__pycache__' in d:
            continue
        for f in files:
            rel = os.path.relpath(os.path.join(d, f), HERE)
            if rel not in skip:
                yield rel


def write_provenance():
    prov_path = p('provenance.json')
    old = json.load(open(prov_path)) if os.path.exists(prov_path) else {}
    files = {}
    for rel in sorted(brand_files()):
        entry = dict(old.get('files', {}).get(rel, {}))
        entry.setdefault('source', 'generated by build.py' if is_generated(rel) else 'TODO: say where this master came from')
        entry['sha256'] = sha(p(rel))
        files[rel] = entry
    out = {'about': 'Where every file in brand/ came from, with its SHA-256. build.py refreshes the hashes.',
           'files': files,
           'surfaces': {s: rel for s, rel in sorted(SPEC.get('outputs', {}).items())}}
    open(prov_path, 'w').write(json.dumps(out, indent=2, ensure_ascii=False) + '\n')


def is_generated(rel):
    return (rel.startswith(('favicon/', 'app-icon/')) and not rel.endswith('.svg') or rel == 'favicon/favicon.svg'
            or rel == 'tokens.css' or any(rel == r['out'] for r in renders()))


def check():
    prov = json.load(open(p('provenance.json')))
    bad = []
    listed = set(prov['files'])
    for rel in brand_files():
        if rel not in listed:
            bad.append(f'brand/{rel}: missing from provenance.json')
    for rel, e in prov['files'].items():
        if not os.path.exists(p(rel)):
            bad.append(f'brand/{rel}: listed but missing')
        elif sha(p(rel)) != e['sha256']:
            bad.append(f'brand/{rel}: hash differs from provenance.json (edit the master, then run build.py)')
    for surface, rel in SPEC.get('outputs', {}).items():
        dst = os.path.join(ROOT, surface)
        if not os.path.exists(dst) or sha(dst) != sha(p(rel)):
            bad.append(f'{surface}: not a copy of brand/{rel} (run python3 brand/build.py)')
    for b in bad:
        print(b)
    print('brand: ok' if not bad else f'brand: {len(bad)} problem(s)')
    return 1 if bad else 0


if __name__ == '__main__':
    if '--check' in sys.argv:
        sys.exit(check())
    build('--resnap' in sys.argv)
